In [3]:
import numpy as np

In [4]:
y_predict=np.array([1,1,0,1])
y_true=np.array([0.30,0.7,1,0.5])


In [5]:
def mae(y_predict,y_true):
    total_error=0
    for yt, yp in zip(y_predict,y_true):
        total_error += abs(yt-yp)
    print("Total error", total_error)
    mae=total_error/len(y_predict)
    print("MAE", mae)

In [6]:
mae(y_predict,y_true)

Total error 2.5
MAE 0.625


In [7]:
np.sum(np.abs(y_predict-y_true))

2.5

In [8]:
np.mean(np.abs(y_predict-y_true))

0.625

In [9]:
np.log(0)

<ipython-input-9-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [10]:
np.log(0.000000000001)

-27.631021115928547

In [11]:
epsilon=1e-15

In [12]:
y_predicted=[1,1,0,1,0]

In [13]:
y_predict_new=[max(i,epsilon) for i in y_predicted ]
y_predict_new

[1, 1, 1e-15, 1, 1e-15]

In [14]:
y_predict_new=[min(i,1-epsilon) for i in y_predict_new ]
y_predict_new

[0.999999999999999, 0.999999999999999, 1e-15, 0.999999999999999, 1e-15]

In [15]:
np.log(y_predict_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -9.99200722e-16,
       -3.45387764e+01])

In [16]:
np.log(y_predicted)

<ipython-input-16-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf,   0., -inf])

In [17]:
def mse(y_predict,y_true):
    total_error=0
    for yt, yp in zip(y_predict,y_true):
        total_error += abs(yt-yp)**2
    print("Total error", total_error)
    mae=total_error/len(y_predict)
    print("MSE", mae)

In [18]:
mse(y_predict,y_true)

Total error 1.83
MSE 0.4575


In [19]:
mse=np.mean(np.square(y_predict-y_true))

In [20]:
mse

0.4575

In [21]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [22]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])